services:
  webshop:
    build:
      context: .
      dockerfile: WebShop.Api/Dockerfile
    container_name: webshop
    ports:
      - "8080:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=MyDatabase;User Id=sa;Password=SuperSafePass.123;TrustServerCertificate=True;"

volumes:
  sqlserver_data:
